[project]
name = "mcp-server-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "openai>=1.70.0",
    "starlette>=0.46.1",
    "uvicorn>=0.34.0",
]
